spring.application.name=El-Youm-8
sheet.size=810980
students.response.size.max=1000

# Database Config (you can select 'mysql' , 'mssql' or 'postgres')
spring.profiles.active=${DB_TYPE:postgres}


spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.thymeleaf.cache=false
#logging.level.org.thymeleaf=DEBUG
#logging.level.org.springframework.web=DEBUG
spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.check-template-location=true
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=debug


springdoc.swagger-ui.path=/docs
#spring.profiles.active=prod

#management.endpoints.web.exposure.include=*

#For Wrong Routes Ex Handling
#spring.web.resources.add-mappings=false
#server.error.whitelabel.enabled=false